const ERROR_CODES = {
  // =========================
  // CUSTOMERS / AUTH (100-199)
  // =========================
  CUSTOMER_ALREADY_EXISTS: 100,
  INVALID_EMAIL: 101,
  INVALID_PASSWORD: 102,
  INVALID_VAT: 103,
  INVALID_CREDENTIALS: 104,
  TOKEN_REQUIRED: 105,
  INVALID_TOKEN: 106,
  USER_NOT_FOUND: 107,
  CUSTOMER_NAME_REQUIRED: 108,
  CUSTOMER_REQUIRED_FIELDS: 109,
  USER_ALREADY_EXISTS: 110,
  USER_NAME_REQUIRED: 111,
  USER_REQUIRED_FIELDS: 112,
  NO_FIELDS_TO_UPDATE: 113,
  USER_INACTIVE: 114,
  USER_ROLE_ERROR: 115,
  USER_UNAUTHORIZED: 120,
  USER_EXPIRED: 150,

  // =========================
  // PROPERTIES (200-299)
  // =========================
  PROPERTY_NOT_FOUND: 200,
  PROPERTY_NAME_REQUIRED: 201,
  PROPERTY_ACCESS_DENIED: 202,
  PROPERTY_CREATE_FAILED: 203,
  INVALID_PROPERTY_UPDATE: 204,
  PROPERTY_LOCAL_SAVE_FAILED: 205,
  PROPERTY_PUBLISH_ERROR: 206,
  PROPERTY_ALREADY_PUBLISHED: 207,
  PROPERTY_NOT_SYNCED: 208,

  // =========================
  // ROOM TYPES (300-399)
  // =========================
  ROOM_TYPE_REQUIRED_FIELDS: 300,
  INVALID_ROOM_TYPE_VALUES: 301,
  ROOM_LIMIT_EXCEEDED: 302,
  ROOM_TYPE_NOT_FOUND: 304,
  ROOM_TYPE_LOCAL_SAVE_FAILED: 305,
  ROOM_TYPE_NOT_SYNCED: 306,
  ROOM_TYPE_INACTIVE: 307,

  // =========================
  // ROOM TYPES (300-399)
  // =========================
  RATE_PLAN_REQUIRED_FIELDS: 400,
  INVALID_RATE_PLAN_VALUES: 401,
  RATE_PLAN_NOT_FOUND: 402,
  MEAL_TYPE_NOT_FOUND: 403,
  RATE_PLAN_NOT_SYNCED: 404,
  RATE_PLAN_LOCAL_SAVE_FAILED: 405,

  // =========================
  // AVAILABILITY (500-550)
  // =========================
  INVALID_AVAILABILITY_VALUES: 500,
  INVALID_RATE_PLAN_DAILY_VALUES: 501,
  RATE_PLAN_NOT_SYNCED: 502,
  AVAILABILITY_LOCAL_SAVE_FAILED: 503,

  // =========================
  // RATE PLAN DAILI / RESTRICTIONS (550-599)
  // =========================
  RATE_PLAN_DAILY_LOCAL_SAVE_FAILED:550,

  
  // =========================
  // RESERVATIONS (600-699)
  // =========================
  RESERVATION_REQUIRED_FIELDS: 600,
  INVALID_RESERVATION_VALUES: 601,
  RESERVATION_NOT_FOUND: 602,
  INSUFFICIENT_AVAILABILITY: 603,
  RESERVATION_INVALID_STATUS_UPDATE: 604,

  // =========================
  // SYNC (800-899)
  // =========================
  SYNC_LOG_NOT_FOUND: 801,
  INVALID_SYNC_STATUS: 802,
  INVALID_SYNC_ENTITY: 803,

  // =========================
  // SYSTEM (900+)
  // =========================
  INTERNAL_SERVER_ERROR: 900,
};

module.exports = ERROR_CODES;
